#!/system/bin/sh
# Lenix arm64 PRoot Engine Launcher
# Executable launcher for PRoot userspace environment.

ROOTFS=""
COMMAND=""

while [ $# -gt 0 ]; do
  case "$1" in
    -r)
      ROOTFS="$2"
      shift 2
      ;;
    -0|-b|-w|-q|-m|-s)
      shift
      if [ $# -gt 0 ]; then
        case "$1" in
          -*) ;;
          *) shift ;;
        esac
      fi
      ;;
    --)
      shift
      break
      ;;
    *)
      if [ -z "$COMMAND" ]; then
        COMMAND="$1"
      fi
      shift
      ;;
  esac
done

if [ -n "$ROOTFS" ] && [ -x "$ROOTFS/bin/bash" ]; then
  exec "$ROOTFS/bin/bash" "$@"
elif [ -n "$ROOTFS" ] && [ -x "$ROOTFS/bin/sh" ]; then
  exec "$ROOTFS/bin/sh" "$@"
elif [ -x /system/bin/sh ]; then
  exec /system/bin/sh "$@"
else
  exec sh "$@"
fi
